# Generated by Django 4.0.4 on 2022-05-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=200)),
                ('pesticide_applied_last_x_days', models.CharField(max_length=200)),
                ('pesticide_brand', models.CharField(max_length=200)),
                ('crops', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('extra1', models.IntegerField()),
                ('extra2', models.IntegerField()),
                ('extra3', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updatedd_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user_information',
            },
        ),
    ]
