# Generated by Django 4.0.4 on 2022-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biosensorapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='updatedd_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='extra1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='extra2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='extra3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
