# Generated by Django 4.0.4 on 2022-05-25 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biosensorapp', '0002_rename_updatedd_at_userinformation_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiosensorTestType',
            fields=[
                ('biosensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('biosensor_test_name', models.CharField(max_length=200)),
                ('details', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('attributes_required', models.TextField()),
                ('extra2', models.IntegerField(blank=True, default=None, null=True)),
                ('extra3', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'biosensor_test_type',
            },
        ),
        migrations.CreateModel(
            name='CholinesteraseType',
            fields=[
                ('cholinesterase_id', models.AutoField(primary_key=True, serialize=False)),
                ('cholinesterase_name', models.CharField(max_length=200)),
                ('extra2', models.IntegerField(blank=True, default=None, null=True)),
                ('extra3', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'cholinesterase_type',
            },
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='extra1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='extra2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='extra3',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_time', models.DateTimeField()),
                ('activity', models.FloatField()),
                ('inhibition', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('baseline', models.FloatField()),
                ('comments', models.TextField()),
                ('extra2', models.IntegerField(blank=True, default=None, null=True)),
                ('extra3', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=200)),
                ('biosensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosensorapp.biosensortesttype')),
                ('cholinesterase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosensorapp.cholinesterasetype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biosensorapp.userinformation')),
            ],
            options={
                'db_table': 'sensor_data',
            },
        ),
    ]
