# Generated by Django 4.0.4 on 2022-05-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biosensorapp', '0004_remove_sensordata_biosensor_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiosensorTestType',
        ),
        migrations.DeleteModel(
            name='CholinesteraseType',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='extra2',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='extra3',
        ),
    ]
