# Generated by Django 2.1.15 on 2022-06-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biosensorapp', '0005_delete_biosensortesttype_delete_cholinesterasetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='extra1',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='extra2',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='extra3',
        ),
    ]
